### ISSUE TITLE
ADS1115 and Joystick Library refuses to upload

### ISSUE THREAD

**Issue by MorGuux** [MHeironimus/ArduinoJoystickLibrary#106]
## Description of Issue
Tested example sketch from Adafruit ADS1X15 library, uploaded to leonardo and tested in serial monitor. Runs fine.

Created a small sketch to get readings and set joystick axis's to values, doesn't upload. Seems to disconnect twice and then stay on uploading. After about 20 seconds, get "Couldn't find a Board on the selected port. Check that you have the correct port selected. If it is correct, try pressing the board's reset button after initiating the upload" error.

Reuploaded the example sketch fine and tested, so the problem has to be with the sketch, or joystick lib. Messed around, disabling things, changing delay etc, nothing seems to make it upload.

Did try the setAxisRange on all three, but no change.

## Technical Details

- Arduino Leonardo
- Windows 10
- Arduino IDE 1.8.8

## Sketch File that Reproduces Issue

~~~C
#include <Joystick.h>

#include <Wire.h>
#include <Adafruit_ADS1015.h>

Joystick_ Joystick;
Adafruit_ADS1115 ads;  /* Use this for the 16-bit version */

void setup() 
{

  // Initialize Joystick Library
  Joystick.begin();
  ads.begin();
 
}

void loop() 
{

  Joystick.setThrottle(ads.readADC_SingleEnded(0));
  Joystick.setRxAxis(ads.readADC_SingleEnded(1));
  Joystick.setRyAxis(ads.readADC_SingleEnded(2));

  delay(100);
}

~~~

## Wiring Details
Nothing relevant as example sketch runs fine and returns all three pot inputs in 16bit signed format (-32767 to 32767), although obviously, no negative values will be returned as VCC = 5V.

**Comment by MorGuux** [comment]
Does upload, enabled verbose logging and get "
avrdude done.  Thank you.", don't know why I get the last warning, but it's irrelevant.

**Comment by Velardop** [comment]
I know this topic is closed. I won't open another one. So dry the code that works.

#include <Wire.h>
#include <Joystick.h>
#include <Adafruit_ADS1X15.h>

Joystick_ Joystick(JOYSTICK_DEFAULT_REPORT_ID,JOYSTICK_TYPE_GAMEPAD, 8, 0, // Button Count, Hat Switch Count
  false, false,false,     // X and Y, but no Z Axis
  true, true, false,   // No Rx, Ry, or Rz
  false, true,          // No rudder or throttle
  false, false, false);  // No accelerator, brake, or steering

Adafruit_ADS1115 ads;

// ------  declaration and initialization of variables
//
int Brake  = 0;
int Gas    = 0;
int Clutch = 0;
int32_t rangeMax = 65535;
//
//------//


void setup() {

  // The ADC input range (or gain) can be changed via the following
  // functions, but be careful never to exceed VDD +0.3V max, or to
  // exceed the upper and lower limits if you adjust the input range!
  // Setting these values incorrectly may destroy your ADC!
  //                                                             ADS1015  ADS1115
  //                                                             -------  -------
  // ads.setGain(GAIN_TWOTHIRDS);  // 2/3x gain +/- 6.144V  1 bit = 3mV      0.1875mV (default)
     ads.setGain(GAIN_ONE);        // 1x gain   +/- 4.096V  1 bit = 2mV      0.125mV
  // ads.setGain(GAIN_TWO);        // 2x gain   +/- 2.048V  1 bit = 1mV      0.0625mV
  // ads.setGain(GAIN_FOUR);       // 4x gain   +/- 1.024V  1 bit = 0.5mV    0.03125mV
  // ads.setGain(GAIN_EIGHT);      // 8x gain   +/- 0.512V  1 bit = 0.25mV   0.015625mV
  // ads.setGain(GAIN_SIXTEEN);    // 16x gain  +/- 0.256V  1 bit = 0.125mV  0.0078125mV

  Serial.begin(9600);
  ads.begin();
  Joystick.begin();

}

void loop() {
  // put your main code here, to run repeatedly:

int16_t adc1, adc2;
int adc0;

adc1 = ads.readADC_SingleEnded(1);  // read the pin a1 value from ads1115
adc2 = ads.readADC_SingleEnded(2);  // read the pin a2 value from ads1115
adc0 = analogRead(A0);              // read the pin A0 value from arduino to micro

Joystick.setRxAxisRange(0,rangeMax); // Setting values between 0 to 65535 (2^16)
Joystick.setRxAxis(Brake);           // setting Brake value

Joystick.setThrottleRange(0,rangeMax); //Setting values between 0 to 65535 (2^16)
Joystick.setThrottle(Gas);             // setting gas value

Joystick.setRyAxisRange(0,1023); //Setting values between 0 to 1023 (2^10)
Joystick.setRyAxis(Clutch);      // setting  Clutch value

Clutch = adc0;  // Stores the value read by the ads.readADC_SingleEnded(1) function
Gas    = adc2;  // Stores the value read by the ads.readADC_SingleEnded(2) function
Brake  = adc1;  // Stores the value read by the analogRead)(A0) function

}
