### ISSUE TITLE
Remove the axes

### ISSUE THREAD

**Issue by Katoz96** [MHeironimus/ArduinoJoystickLibrary#107]
Hi, 

I built a handbrake for my simulator using an Arduino ProMicro on Windows 10 following [this](https://www.youtube.com/watch?v=kv0FTpRLFMY) tutorial.

This is the code included in the tutorial
```
#include <Joystick.h>

void setup()

{
  pinMode(A1, INPUT); 
  Joystick.begin();
}

const int pinToButtonMap = A1;

void loop()

{
  int pot = analogRead(A1);
  int mapped = map(pot,0,1023,0,255);
  {Joystick.setThrottle(mapped);}
}
```
Everything works fine but the Z axis it's stuck at 50% even after calibrating it, in some games it's not a problem but in others it makes them unplayable. 

![arduinoleonardo](https://user-images.githubusercontent.com/47279240/52167713-d145e900-271f-11e9-811e-5e12077d77d3.PNG)
At first I wanted to ask how to solve this problem but then it occurred to me that it would be nice to have only one axis for the handbrake. 

So, it's possible to remove everything else (including the buttons) and leave only one axis?

Thanks in advance

**Comment by MHeironimus** [comment]
If you use the latest version of the library, you can control what features are presented to the host computer. See https://github.com/MHeironimus/ArduinoJoystickLibrary#joystick_ for more details.
