### ISSUE TITLE
[question] Is it possible to make the arduino be recognized as a PS4 controller to the PS4 ?

### ISSUE THREAD

**Issue by Lion4K** [MHeironimus/ArduinoJoystickLibrary#115]
I wanna make an Arcade like controller but I don't wanna sacrifice a controller to do it.
Also I know that there's boards made for this, but I already have an arduino here and I wanna make something that I could simply flash another firmware to be used on the xbox one as well and back and forth.

**Comment by warewolf** [comment]
Not easily, there's complex protocol negotiation (nonstandard) that goes between a playstation and the controller.
