### ISSUE TITLE
hello i did everything in the forms like said and it was almost down to the last line of the sketch but i received an error code 

### ISSUE THREAD

**Issue by Ector35** [MHeironimus/ArduinoJoystickLibrary#124]
## Description of Issue
Enter description of issue here.

## Technical Details

- Arduino Board (e.g. Arduino Leonardo): 
- Host OS (e.g. Windows 10):
- Arduino IDE Version (e.g. 1.8.3):

## Sketch File that Reproduces Issue

~~~
Sketch file goes here (if applicable)
~~~

## Wiring Details

Any details about pin wirings that may be relevant.

**Comment by MHeironimus** [comment]
You need to provide details of the error you received. It would also be good to include the Sketch file that was giving you the error.

**Comment by MHeironimus** [comment]
Could not reproduce issue.
