### ISSUE TITLE
No correct  library 

### ISSUE THREAD

**Issue by Silverker** [MHeironimus/ArduinoJoystickLibrary#125]
Hey,
I'm trying to make usb gamepad for RaspberryPi and want to upload Your library to AtMega32u4
and the program says there is no correct library.
Please help.

**Comment by kipnlilo** [comment]
I have the same message for the 32 button box
Specified folder/zip file does not contain a valid library.
Please help.

**Comment by scruss** [comment]
see [#97](https://github.com/MHeironimus/ArduinoJoystickLibrary/issues/97) and/or read the [Installation Instructions](https://github.com/MHeironimus/ArduinoJoystickLibrary#installation-instructions)
