### ISSUE TITLE
Expected ',' before '.' token

### ISSUE THREAD

**Issue by kilmer83** [MHeironimus/ArduinoJoystickLibrary#139]
## Description of Issue
i am setting up the push buttons and im using the Joystick.pressButton and Joystick.releaseButton and once i get to the last button i get this error but it says all the other ones are fine the problem is in the "[Joystick.releaseButton(13)];"

## Technical Details

- Arduino Board (e.g. Arduino Leonardo): Arduino Micrp
- Host OS (e.g. Windows 10): Windows 10
- Arduino IDE Version (e.g. 1.8.3):

## Sketch File that Reproduces Issue
#include <Joystick.h>
#include <Wire.h>

Joystick_ Joystick;
int RxAxis_ = 0;
int RyAxis_ = 0;
int XAxis_ = 0;
int YAxis_ = 0;

const bool initAutoSendState = true;

void setup() {
  pinMode(SS, INPUT_PULLUP); //Left
  pinMode(1, INPUT_PULLUP); //Right
  pinMode(13, INPUT_PULLUP); //UP
  pinMode(MOSI, INPUT_PULLUP); //Down
  pinMode(4, INPUT_PULLUP); //A
  pinMode(5, INPUT_PULLUP); //B
  pinMode(0, INPUT_PULLUP); //Y
  pinMode(6, INPUT_PULLUP); //X
  pinMode(7, INPUT_PULLUP); //Start
  pinMode(8, INPUT_PULLUP); //Select
  pinMode(11, INPUT_PULLUP); //Left Trigger
  pinMode(12, INPUT_PULLUP); //Right Trigger
  pinMode(9, INPUT_PULLUP); //Left Bumper
  pinMode(10, INPUT_PULLUP); //Right Bumper
  pinMode(SDA, INPUT);
    Joystick.begin();
  

}

void loop() {

RxAxis_ = analogRead(A5); //Variable is equal to the input from analog pin "A5"
  RxAxis_ = map(RxAxis_,0,1023,255,0); //Mapping Variable
  Joystick.setRxAxis(RxAxis_); //links joysticks right x axis to the input variable

   RyAxis_ = analogRead(A4);
   RyAxis_ = map(RyAxis_,1023,0,255,0);
   Joystick.setRyAxis(RyAxis_);

   XAxis_ = analogRead(A2);
   XAxis_ = map(XAxis_,0,1023,255,0);
   Joystick.setXAxis(XAxis_);

   YAxis_ = analogRead(A1);
   YAxis_ = map(YAxis_,0,1023,255,0);
   Joystick.setYAxis(YAxis_);

if (digitalRead(SS) == LOW)
[Joystick.pressButton(0)];
else
[Joystick.releaseButton(0)];

if (digitalRead(1) == LOW)
[Joystick.pressButton(1)];
else
[Joystick.releaseButton(1)];

if (digitalRead(13) == LOW)
[Joystick.pressButton(2)];
else
[Joystick.releaseButoon(2)];

if (digitalRead(MOSI) == LOW)
[Joystick.pressButton(3)];
else
[Joystick.releaseButton(3)];

if (digitalRead(4) == LOW)
[Joystick.pressButton(4)];
else
[Joystick.releaseButton(4)];

if (digitalRead(5) == LOW)
[Joystick.pressButton(5)];
else
[Joystick.releaseButton(5)];

if digitalRead(0) == LOW)
[Joystick.pressButton(6)];
else
[Joystick.releaseButton(6)];

if digitalRead(6) == LOW)
[Joystick.pressButton(7)];
else
[Joystick.releaseButton(7)];

if digitalRead(7) == LOW)
[Joystick.pressButton(8)];
else
[Joystick.releaseButton(8)];

if digitalRead(8) == LOW)
[Joystick.pressButton(9)];
else
[Joystick.releaseButton(9)];

if digitalRead(11) == LOW)
[Joystick.pressButton(10)];
else
[Joystick.releaseButton(10)];

if digitalRead(12) == LOW)
[Joystick.pressButton(11)];
else
[Joystick.releaseButton(11)];

if digitalRead(9) == LOW)
[Joystick.pressButton(12)];
else
[Joystick.releaseButton(12)];

if digitalRead(10) == LOW)
[Joystick.pressButton(13)];
else
[Joystick.releaseButton(13)];

  
delay(10);
}

## Wiring Details
Any pin wiring details that may be relevant.

**Comment by Bustean** [comment]
First off, from what is posted here, the syntax for the if statements is all over the place, even missing the first bracket of each if (true for all of them).

Correct: if(...) { } else { }

Therefore this:

>if digitalRead(10) == LOW)
[Joystick.pressButton(13)];
else
[Joystick.releaseButton(13)];

Should look like this:

`if (digitalRead(10) == LOW) {
     Joystick.pressButton(13);
}
else {
     Joystick.releaseButton(13);
}`
