### ISSUE TITLE
Type set to JOYSTICK_TYPE_GAMEPAD, yet Win10 detects Arduino Micro as joystick

### ISSUE THREAD

**Issue by ftsdesign** [MHeironimus/ArduinoJoystickLibrary#143]
## Description of Issue
No application on Win10 detects Arduino Micro as a gamepad (tried Game Controller Tester, as well as multiple games). In Game Controllers control panel it is also shown as joystick.

## Technical Details

- Arduino Board (e.g. Arduino Leonardo): Arduino Micro
- Host OS (e.g. Windows 10): Win10
- Arduino IDE Version (e.g. 1.8.3): 1.8.12

## Sketch File that Reproduces Issue

~~~
Joystick_ Joystick = Joystick_(
    JOYSTICK_DEFAULT_REPORT_ID, 
    JOYSTICK_TYPE_GAMEPAD,
    6, //buttonCount
    0, //hatSwitchCount
    true, //includeXAxis
    true, //includeYAxis
    false, //includeZAxis
    false, //includeRxAxis
    false, //includeRyAxis
    false, //includeRzAxis
    false, //includeRudder
    true, //includeThrottle
    false, //includeAccelerator
    false, //includeBrake
    false //includeSteering
    );
~~~

## Wiring Details
Any pin wiring details that may be relevant.

**Comment by MHeironimus** [comment]
This is expected. The `joystickType` is a pretty low-level setting. See the Universal Serial Bus (USB)
HID Usage Tables documentation for more details (https://usb.org/sites/default/files/documents/hut1_12v2.pdf). Look for section 4.1 (Application Usages).
