### ISSUE TITLE
The Joystick library can only be used with a USB MCU

### ISSUE THREAD

**Issue by MitchK** [MHeironimus/ArduinoJoystickLibrary#144]
## Description of Issue

Hi, I'm very new to Arduino development. When uploading the `JoystickTest` exampleto my board, I get this error:

> The Joystick library can only be used with a USB MCU (e.g. Arduino Leonardo, Arduino Micro, etc.).

It seems like the library does only support Arduino Leonardo or Micro. Is there a way/workaround to get it to run on a Mega 2560 or is there no way around buying a new board?

Thank you!

## Technical Details

- Arduino Board (e.g. Arduino Leonardo): Mega 2560
- Host OS (e.g. Windows 10): Windows 10
- Arduino IDE Version (e.g. 1.8.3):

## Sketch File that Reproduces Issue

JoystickTest sketch

## Wiring Details

N/A

**Comment by MHeironimus** [comment]
That is correct. This library is only supported on the cards listed in the wiki: https://github.com/MHeironimus/ArduinoJoystickLibrary/wiki/Supported-Boards

**Comment by MitchK** [comment]
Thanks! Just got my Leonardo today, closing this.
