### ISSUE TITLE
Can't add the library

### ISSUE THREAD

**Issue by qwertyalfa** [MHeironimus/ArduinoJoystickLibrary#145]
When I try to add the library from ZIP / folder, I cant do so. I get information that there is no correct library in that directory. Can anyone help me?

PS
OS: Win 10
Arduino IDE version: 1.8.12 (windows store)
Downgrading did not work

**Comment by CryptoAngel** [comment]
To which folder you're trying to copy the file? Have extract it? The folder is read only? What error message you see?

**Comment by qwertyalfa** [comment]
I managet to fix it, but thanks for a reply :)
Something was odd with some of my drivers, after updating it works like a charm.

**Comment by CryptoAngel** [comment]
By the way, do you know if this is the most updated version of ArduinoJoystick?
I building my own joystick and I need X,Y,Z and those buttons and the hat buttons but I am not sure this is the perfect solution. Also there he did not include the wire connections...
Regards
