### ISSUE TITLE
Add support for Android/iOS devices

### ISSUE THREAD

**Issue by tomxposed** [MHeironimus/ArduinoJoystickLibrary#149]
The library **does not work on my android phone**. I don't know whether it is a bug or not. If it is not implemented please do so, it will be very useful for games like PUBG and COD Mobile

**Comment by BusteanHAN** [comment]
The library works on the USB HID standard which is not supported by phones. The whole point of HID is to not use drivers, but to connect an input device to any phone you need a driver.

**Comment by tomxposed** [comment]
The keyboard library used is perfectly working on the android devices

**Comment by tomxposed** [comment]
@BusteanHAN I have implemented the library for my [iBus-Joystick](https://github.com/tomxposed/iBus-Joystick#ibus-joystick) project and it works fine in Android, iOS, Mac, and Windows machines without any drivers :-)
