### ISSUE TITLE
Help! I need an older Version

### ISSUE THREAD

**Issue by HitZme** [MHeironimus/ArduinoJoystickLibrary#163]
Im sorry for the wrong topic for this problem. 
I need the version 2.0.5 please.

**Comment by MHeironimus** [comment]
I think this link will get you what you want: https://github.com/MHeironimus/ArduinoJoystickLibrary/tree/368612304c3ddf1ee54c2705d83e37ab2d8460aa

**Comment by HitZme** [comment]
Thank u so fucking much, I were searching like 6 hours for this problem!
And now it works finally. Thanks!!

Am Di., 1. Sept. 2020 um 01:41 Uhr schrieb Matthew Heironimus <
notifications@github.com>:
