### ISSUE TITLE
In Game Controllers everything works fine but erratic in games

### ISSUE THREAD

**Issue by EloyFarina** [MHeironimus/ArduinoJoystickLibrary#164]
Board: Arduino Leonardo R3 (clone but looks identical to the original)
SO: Windows 10 x64
Joystick: SEGA Genesis MK-1470 6-Button Turbo Controller (clone)
Code used: "GamepadExample.ino" (without modify)

In Game Controllers the Arduino Leonardo joystick works as expected. D-Pad and the B button works correctly, however in all games that I've tested, it moves to the left continuously, even if I touch B button.

Not sure if this behavior is related to the code. Any help will be appreciated.

![2020-09-03 21_29_37-Propiedades de Arduino Leonardo](https://user-images.githubusercontent.com/28933311/92186280-a4dadd00-ee2c-11ea-80e0-9c841cf28e24.png)

![Sin título](https://user-images.githubusercontent.com/28933311/92186094-08183f80-ee2c-11ea-88b0-571b432ee5a0.jpg)

Regards

**Comment by EloyFarina** [comment]
I fixed the issue with x360ce software, creating a virtual XBOX 360 joystick, remapping D-PAD and the button, and hiding the Arduino Leonardo in Game Controllers panel with this same software.

**Comment by MHeironimus** [comment]
Glad you were about to get your issue resolved.
