### ISSUE TITLE
Arduino DUE 1.6.11 not supported.

### ISSUE THREAD

**Issue by HappyFabian** [MHeironimus/ArduinoJoystickLibrary#17]
For some reason, I can not initialize the Joystick emulator using my Arduino DUE.

I am using Arduino IDE 1.6.11, and using Windows 10

**Comment by MHeironimus** [comment]
The only two boards I have personally tested with are the Arduino Leonardo and the Arduino Micro. I have had people tell me Version 1.x of the library will work with the Arduino Due, but I know the Version 2.x of the library will not work with the Arduino Due.

What version of the library were you trying to use?
