### ISSUE TITLE
LGPL / GPL ?

### ISSUE THREAD

**Issue by fishchisel** [MHeironimus/ArduinoJoystickLibrary#18]
Hello,

Thanks for writing this code, it's really handy. Looking through it I noticed a license conflict: in the root of the repository the LICENSE file says that the license is GPL, but each of the source files have a header that indicates the license to be LGPL. I wonder which is the license that you intend?

**Comment by MHeironimus** [comment]
Thank you for letting me know about this discrepancy. I have updated the LICENSE file to align with what was specified in the source files. This library is released with the LGPL.
