### ISSUE TITLE
How to get encoder switches to work?

### ISSUE THREAD

**Issue by laserbeak** [MHeironimus/ArduinoJoystickLibrary#192]
Hi,
Orignially, I used this code to get encoder switches to work:

        #define CLK_PIN  1
        #define DATA_PIN 0
        #define BUTTON  2
    
    void setup() {
       pinMode(CLK_PIN,INPUT);
       pinMode(DATA_PIN,INPUT);
       pinMode(BUTTON, INPUT_PULLUP);
    
       Serial.begin(9600);
       Serial.println("Rotary Encoder KY-040");
    }

    void loop() {
    static uint16_t state=0,counter=0;
    
        delayMicroseconds(100); // Simulate doing somehing else as well.
    
        state=(state<<1) | digitalRead(CLK_PIN) | 0xe000;
    
        if (state==0xf000){
           state=0x0000;
           if(digitalRead(DATA_PIN))
             counter++;
           else
             counter--;
           Serial.println(counter);
        }
    
        if (digitalRead(BUTTON)==0) {
    
          delay(10);
          if (digitalRead(BUTTON)==0) {
              Serial.println("Next Detent");
              while(digitalRead(BUTTON)==0);
          }
       }
    }

How would I use your library to achieve something like this?

**Comment by VkTheProgrammer17** [comment]
Encoder switches are just like normal 2-pin push button switches, so whatever code you have written for your switches, use that code for these encoder switches.

**Comment by laserbeak** [comment]
I don't follow. Will including joystick.h make this code visible to the windows directInput  Game Controller manager?

**Comment by VkTheProgrammer17** [comment]
you are welcome
