### ISSUE TITLE
Analog resolution

### ISSUE THREAD

**Issue by Clamb94** [MHeironimus/ArduinoJoystickLibrary#20]
Hi, 
is there a specific reason why the axis only go from -127 to 127? The resolution is rather low when compared to the possible 1024 steps from the ADC on the Arduino Leonardo.

**Comment by MHeironimus** [comment]
If you need higher precision in your axis values, see Version 2.0 of the library: https://github.com/MHeironimus/ArduinoJoystickLibrary/tree/version-2.0
