### ISSUE TITLE
Higher axis accuracy than -127 to 127? Say -512 to 512?

### ISSUE THREAD

**Issue by KriLL3** [MHeironimus/ArduinoJoystickLibrary#21]
Arduinos analog ports are 10bit (zero and due are 12bit) so go from 0-1023, but this library only lets you use 8bit, 1/4 of the resolution, I'd really like an option to go higher resolution on one/more axis, 8bit isn't enough to make a precision joystick or similar.

**Comment by MHeironimus** [comment]
Version 2.0 of this library supports upto 16-bix axis values. See https://github.com/MHeironimus/ArduinoJoystickLibrary/tree/version-2.0 for more details.

**Comment by KriLL3** [comment]
Ah, my apologies. :)
