### ISSUE TITLE
Error thrown when trying to add .ZIP library

### ISSUE THREAD

**Issue by dadleybs** [MHeironimus/ArduinoJoystickLibrary#217]
Hey there, getting the following error when attempting to upload the .ZIP library to Arduino IDE 2.0.0-beta.11. Any ideas?

`Error: Request installZip failed with message: 2 UNKNOWN: library is not valid: missing header file "ArduinoJoystickLibrary-version-2.0.h"`

Thanks!

**Comment by ERJP** [comment]
I am having the same issue as above, has anyone found a solution to this by chance?

**Comment by dadleybs** [comment]
SOLUTION: It appears the code doesn't agree with the beta 2.0.0 version of the Arduino IDE. When using Arduino IDE 1.8.16, everything worked as expected. Hope this helps!
