### ISSUE TITLE
Will this work on a ESP8266 Nodemcu Board?

### ISSUE THREAD

**Issue by simtcrom** [MHeironimus/ArduinoJoystickLibrary#222]
Please indicate which board you would like to see supported.
ESP8266 Nodemcu

I tried loading the library and trying to flash JoystickTest get below error,

In file included from C:\Users\sim_t\Documents\Arduino\libraries\ArduinoJoystickLibrary-version-2.0\src/Joystick.h:24:0,
                 from C:\Users\sim_t\Documents\Arduino\libraries\ArduinoJoystickLibrary-version-2.0\examples\JoystickTest\JoystickTest.ino:13:
C:\Users\sim_t\Documents\Arduino\libraries\ArduinoJoystickLibrary-version-2.0\src/DynamicHID/DynamicHID.h:37:28: fatal error: PluggableUSB.h: No such file or directory
   #include "PluggableUSB.h"
                            ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by positron96** [comment]
ESP8266 has no hardware USB, so it's not possible to port the library.

**Comment by MHeironimus** [comment]
See the following wiki page for the list of supported boards: https://github.com/MHeironimus/ArduinoJoystickLibrary/wiki/Supported-Boards
