### ISSUE TITLE
Unable to deal with more than 2 controllers in a single sketch

### ISSUE THREAD

**Issue by guillaumeparent** [MHeironimus/ArduinoJoystickLibrary#236]
## Description of Issue
As stated in the title, I am unable to create a sketch able to set more than 2 controllers.
The discussion started in [Mathiew's blog](http://mheironimus.blogspot.com/2016/11/arduino-joystick-library-version-20.html?showComment=1647775571467#c6579748545785113185).

To summarize, I manage to create sketches dealing with 2 controllers, but as soon as I try to deal with more than 2 controllers only the 2 first ones are properly defined.

I attach in the following a minimal reproducible example attempting to define 4 controllers with 1 button each.
As one can see on the attache picture, only the 2 first (0x10 and 0x11) controllers are properly detected. The 2 last ones (0x12 and 0x14) are not. The axis are recognized as buttons only.

<img width="1792" alt="Capture d’écran 2022-03-21 à 09 24 19" src="https://user-images.githubusercontent.com/64403105/159227043-e97bc4df-ebfd-4169-b761-d5583a84b94b.png">

## Technical Details

- Arduino Board: Arcuino Micro and Arduino Pro Micro: 
- Host OS: MacOS (Catalina)
- Arduino IDE Version: 1.8.19
- Joystick library version: 2.0.7

## Sketch File that Reproduces Issue

~~~
#include <Joystick.h>

#define NbrGamePad 4

Joystick_ Joystick[NbrGamePad] = {
Joystick_(0x10, JOYSTICK_TYPE_GAMEPAD, 1, 0, true, true, false, false, false, false, false, false, false, false, false),
Joystick_(0x11, JOYSTICK_TYPE_GAMEPAD, 1, 0, true, true, false, false, false, false, false, false, false, false, false),
Joystick_(0x12, JOYSTICK_TYPE_GAMEPAD, 1, 0, true, true, false, false, false, false, false, false, false, false, false),
Joystick_(0x13, JOYSTICK_TYPE_GAMEPAD, 1, 0, true, true, false, false, false, false, false, false, false, false, false)
};

void setup() {
// put your setup code here, to run once:

}

void loop() {
// put your main code here, to run repeatedly:

}
~~~

## Wiring Details
Any pin wiring details that may be relevant.

**Comment by MHeironimus** [comment]
The sketch file above appears to work correctly on Windows 10. It may be a MacOS issue.

For example:

![image](https://user-images.githubusercontent.com/5286686/159272353-48c73d82-5c9c-46b8-b289-797382f5293a.png)

First Controller:

![image](https://user-images.githubusercontent.com/5286686/159272443-80393cc2-1fd7-4f29-89f4-179ac65bf743.png)

Fourth Controller:

![image](https://user-images.githubusercontent.com/5286686/159272542-6a829a7f-a8fa-4092-a564-3868c2a1a7a5.png)

The second and third look the same.

I know Linux machines need an adjustment to work correctly if more than one controller is defined (see https://github.com/MHeironimus/ArduinoJoystickLibrary/wiki/FAQ#linux-support for more details). Maybe there is something equivalent for the Mac.

**Comment by guillaumeparent** [comment]
Ok, I found the problem. It was indeed the issue mentioned [here](http://mheironimus.blogspot.com/2015/09/linux-support-for-arduino-leonardo.html).
I tested the method on a Raspberry Pi (on which I experienced the same 2 controller limitation) and it worked. Now I can see 4 controllers.

Thank you for the help !
