### ISSUE TITLE
Arduino Micro and 32 Buttons

### ISSUE THREAD

**Issue by dimigav** [MHeironimus/ArduinoJoystickLibrary#270]
I noticed that you support up to 32 buttons, but Arduino Micro cannot handle too much buttons.
So, if someone want to use 4 analog inputs for joystick, 2 analog inputs for rudder and lets say 23 buttons is impossible with the code.
Can you provide code for input matrix?

Thanks
Very good job anyway.

**Comment by MHeironimus** [comment]
This library is not focused on how you read buttons or other hardware. It is only focused on making the Arduino appear as a Joystick/Gamepad to the host device. See the [FAQ](https://github.com/MHeironimus/ArduinoJoystickLibrary/wiki/FAQ) section on [Buttons](https://github.com/MHeironimus/ArduinoJoystickLibrary/wiki/FAQ#buttons) for information on how to read values from large numbers of buttons.
