### ISSUE TITLE
Commercial licsense?

### ISSUE THREAD

**Issue by horizoncarguy** [MHeironimus/ArduinoJoystickLibrary#294]
Hello,

is there a way to purchase a commercial license for small projects and if yes how much is it?

Thanks and kind regards,
Paul

**Comment by MHeironimus** [comment]
Thank you for checking. The license on this library allows for commercial usage for free. See https://github.com/MHeironimus/ArduinoJoystickLibrary/blob/master/LICENSE for more details.

The only caveat is if you change the code, please submit a PR with your changes so others can benefit from your modifications.

Good luck with your project.
