### ISSUE TITLE
32 Buttons + 2 hat switch

### ISSUE THREAD

**Issue by Pojer1** [MHeironimus/ArduinoJoystickLibrary#30]
(Sorry I don´t speak english this is traslated with Google Tool)

Hi. I am interested in creating my buttons box, I do not know anything about arduino programming so I read a lot of project examples but don´t find information or examples of how to use the 32 buttons. My idea is to use the 32 buttons and the 2 hat switch which gives a total of 40 buttons. As the arduino leonardo does not have 40 digital ports I imagine that you have to define an array of 8 rows and 5 columns and assign them to the 13 digital ports. But how do I do this? Can you help me? (I do not need any analog ports, just buttons) Thank you very much.

**Comment by MHeironimus** [comment]
There are various ways to read multiple button values with a limited number of inputs. Here are some examples to get you started:

### Use Button Shield
http://spikenzielabs.com/SpikenzieLabs/Button64Shield.html
https://www.tindie.com/products/ElectricLaboratory/lobshield-lots-of-buttons/

### Matrix Scanning Technique
https://learn.sparkfun.com/tutorials/button-pad-hookup-guide

### Using an Analog Pin
http://www.instructables.com/id/How-to-access-5-buttons-through-1-Arduino-input/

### Using a 74HC4067
http://bildr.org/2011/02/cd74hc4067-arduino/
http://tronixstuff.com/2013/08/05/part-review-74hc4067-16-channel-analog-multiplexerdemultiplexer/

Hope one of the links helps,
Matt
