### ISSUE TITLE
compatibility with clones

### ISSUE THREAD

**Issue by Sylverzerom** [MHeironimus/ArduinoJoystickLibrary#46]
First, big thanks to MHeironimus for this awesome library.

I am just giving a feedback, that this library is working fine with a robotdyn micro 32u4. Good thing is, this boards are really cheap (5.85$ with shipping). I am using it for my custom controller with a raspberry pi zero.

best regards,

**Comment by MHeironimus** [comment]
@Sylverzerom  Thanks for the information. I have updated the README to include this board.
#47
