### ISSUE TITLE
Invalid library found in

### ISSUE THREAD

**Issue by SoulMaril** [MHeironimus/ArduinoJoystickLibrary#48]
I think there is a new requirement of Arduino IDE 1.8.2 for Libraries. We get this warning/info when compiling "Invalid library found in Drive://Path"

**Comment by MHeironimus** [comment]
@SoulMaril 
Can you post the Operating System on which you are running the Arduino IDE? Also, can you post the full output of the compilation log that contains the "Invalid library..." message?

**Comment by SoulMaril** [comment]
I am using Windows10 64bit. But right now I can't get the message. Now It works wihout a problem.

**Comment by MHeironimus** [comment]
If you are able to reproduce the issue, please post the details. I am going to close this issue out for now, but will reopen it if needed.
