### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GeorgeNidri** [MHeironimus/ArduinoJoystickLibrary#5]
Hi, 
when I import the joystick library, I get the following error:

> Arduino: 1.7.9 (Windows 8.1), Board: "Arduino Leonardo"
> 
> In file included from sketch_apr19b.ino:1:0:
> 
> C:\Program Files (x86)\Arduino\libraries\Joystick/Joystick.h:24:17: fatal error: HID.h: No such file or directory
> 
>  #include "HID.h"
> 
>                  ^
> 
> compilation terminated.
> 
> Error compiling.
> _

I get that even if I only import the library. Any ideas of why that happens?

Thanks!

**Comment by MHeironimus** [comment]
I have tested this on Arduino IDE 1.6.6, 1.6.7, and 1.6.8. I am not familiar with Arduino: 1.7.9.

**Comment by GeorgeNidri** [comment]
so should I downgrade?

**Comment by GeorgeNidri** [comment]
Yup, it worked. Thanks!

**Comment by j-keiter** [comment]
What worked??  The downgrade?  If so what version did you downgrade to.
Thx Jason
