### ISSUE TITLE
Is it possible to have two joysticks without the rotation value?

### ISSUE THREAD

**Issue by shingtaklam1324** [MHeironimus/ArduinoJoystickLibrary#50]
So I'd like to have a two joystick setup like most game controllers, but the 0deg to 360deg rotation doesn't work for me

**Comment by kennethnakasone** [comment]
By "doesn't work for me", do you mean that you do not require the functionality? If so, I believe you can disable them using by setting the 8th, 9th, and 10th parameters of the Joystick constructor to false.

If you meant that "rotation is not being detected", then sorry but I have no idea at the moment.

**Comment by MHeironimus** [comment]
You are going to need to provide your sketch file and a description of your hardware setup for the group to be able to help you with your issue.

**Comment by MHeironimus** [comment]
I am closing this issue due to a lack of details.
