### ISSUE TITLE
3Joy X 8Axis

### ISSUE THREAD

**Issue by JazzyManSerg** [MHeironimus/ArduinoJoystickLibrary#60]
Hello, Great thx for the Job.
I need 3 joy , which  must have 8axis. So 24 Axis summary.
Can I make it by joystick3.h? What can i change there for my task?

**Comment by MHeironimus** [comment]
I would recommend using the latest version of the Arduino Joystick Library (Version 2.0.4 when I posted this). It can support 3 joysticks with 8 axes each (however, I have heard people sometimes have issues if the axis count gets above 7 per joystick).

**Comment by JazzyManSerg** [comment]
OOO ! Great thx Matthew, yes I have old version. I will try new version at the evening,

**Comment by JazzyManSerg** [comment]
Yeah, Working propperly !!!!Thx !!!!
