### ISSUE TITLE
Games won't recognice my device

### ISSUE THREAD

**Issue by legomolina** [MHeironimus/ArduinoJoystickLibrary#65]
I've constructed a button box for my sim and I'm using your library but it's not working at all. Windows recognices the device as gaming controller but I can't bind any button to any game. This is my code.

```
#include <Joystick.h>

Joystick_ Joystick(JOYSTICK_DEFAULT_REPORT_ID,JOYSTICK_TYPE_GAMEPAD, 19, 0, false, false, false, false, false, false, false, false, false, false, false);

int buttonPins[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, A0, A1, A2, A3, A4, A5};
int buttonPreviousState[] {LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW, LOW};

void setup() { 
    for(int i = 0; i < sizeof(buttonPins); i ++)
        pinMode(buttonPins[i], INPUT);

    Joystick.begin();
}

void loop() {
    buttonPreviousState[0] = pushButton(1, buttonPreviousState[0], 0);
    buttonPreviousState[1] = pushButton(2, buttonPreviousState[1], 1);
    buttonPreviousState[2] = pushButton(3, buttonPreviousState[2], 2);
    buttonPreviousState[3] = pushButton(4, buttonPreviousState[3], 3);
    buttonPreviousState[4] = pushButton(5, buttonPreviousState[4], 4);
    buttonPreviousState[5] = pushButton(6, buttonPreviousState[5], 5);
    buttonPreviousState[6] = pushButton(7, buttonPreviousState[6], 6);
    buttonPreviousState[7] = pushButton(8, buttonPreviousState[7], 7);
    buttonPreviousState[8] = pushButton(9, buttonPreviousState[8], 8);
    buttonPreviousState[9] = pushButton(10, buttonPreviousState[9], 9);
    buttonPreviousState[10] = pushButton(11, buttonPreviousState[10], 10);
    buttonPreviousState[11] = pushButton(12, buttonPreviousState[11], 11);
    buttonPreviousState[12] = pushButton(13, buttonPreviousState[12], 12);
    buttonPreviousState[13] = pushButton(A0, buttonPreviousState[13], 13);
    buttonPreviousState[14] = pushButton(A1, buttonPreviousState[14], 14);
    buttonPreviousState[15] = pushButton(A2, buttonPreviousState[15], 15);
    buttonPreviousState[16] = pushButton(A3, buttonPreviousState[16], 16);
    buttonPreviousState[17] = pushButton(A4, buttonPreviousState[17], 17);
    buttonPreviousState[18] = pushButton(A5, buttonPreviousState[18], 18);
}

int pushButton(int pin, int previousState, int button) {
    int currentState;

    currentState = digitalRead(pin);
  
    if(currentState != previousState) {
        Joystick.setButton(button, currentState);/*
        if(currentState == HIGH)
            Joystick.setButton(button, HI);
        else
            Joystick.setButton(button, currentState);*/
        
        delay(10);
    }

    return currentState;
}
```

Buttons are connected through resistor to arduino pins. I've tested with JOYSTICK_TYPE_GAMEPAD, JOYSTICK_TYPE_JOYSTICK and JOYSTICK_TYPE_MULTI_AXIS but it won't work anyway.

![image](https://user-images.githubusercontent.com/9081996/31313206-065efaac-abdc-11e7-8616-0240f903a17d.png)

![image](https://user-images.githubusercontent.com/9081996/31313209-16b56c92-abdc-11e7-8649-1fd4af0ac959.png)

**Comment by MHeironimus** [comment]
Are you saying the Windows game controller test dialog does not display any of your button presses? If so, I would recommend writing the value of one of the pins out to the Serial Port so you can verify the pins are getting set/pressed the way you expect. I usually put the pins in `INPUT_PULLUP` mode and have the buttons connected to ground.

**Comment by legomolina** [comment]
No, Windows game controller dialog works perfect. But when I execute a game and go to options > controls, I can't bind buttons from the arduino to actions.

**Comment by kingfisher09** [comment]
Did you find a solution to this issue?

**Comment by legomolina** [comment]
No. Just some games allow to interact with Arduino and others no. I'm not sure if it's a problem with this lib or maybe it's a game/Windows issue.

**Comment by kingfisher09** [comment]
I feel like the solution is to mimic the number of inputs of a standard controller. As shown below. 

![image](https://user-images.githubusercontent.com/6705278/81480353-21fc9980-9221-11ea-843b-7a328e4e029c.png)

Rather than like this:
![image](https://user-images.githubusercontent.com/6705278/81480391-6851f880-9221-11ea-8ade-390b1d7cc23a.png)


I think the key to this is editing the Joystick files in the library. I managed to remove the Rudder and Throttle by commenting out parts of the files but unfortunately that stopped the rest of the functionality too. Any ideas?

**Comment by targodan** [comment]
[As per the README](https://github.com/MHeironimus/ArduinoJoystickLibrary#joystick_) you can specify the number of axis and buttons in the constructor.

**Comment by kingfisher09** [comment]
Haha, yes sorry I just noticed that!
