### ISSUE TITLE
there is no motion in the game controller

### ISSUE THREAD

**Issue by Mrtulusoy** [MHeironimus/ArduinoJoystickLibrary#72]
Hello there;
I use translation because I do not speak english

I did everything but I could not get it to work.

I installed the codes as a game controller, but when I pressed the keys there was no movement

**Comment by SoulMaril** [comment]
Kart olarak ne kullanıyorsun?

**Comment by Mrtulusoy** [comment]
@SoulMaril Arduino pro micro klon ama pc leonardo olarak görüyor
